version: "3.9"

services:
  mysql_db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "3306:3306"
    volumes:
      - todo_site_mysql_data:/var/lib/mysql

  django_app:
    build: .
    command: >
      sh -c "/wait_for_mysql.sh python manage.py collectstatic --noinput && python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - mysql_db
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - STATIC_ROOT=/app/static
    volumes:
      - static_volume:/app/static

volumes:
  todo_site_mysql_data:
  static_volume:
